version: '3'
networks:
  pizza-shop.net:
    driver: bridge
services:

  # service api.pizza-shop : api pour la prise de commandes
  #
  api.pizza-shop:
    image: 'canals/php:latest'
    env_file: ./shop.env
    ports:
      - '2080:80'
      - '1443:443'
    volumes:
      - ../shop.pizza-shop/public:/var/www/html
      - ../shop.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      pizza-shop.net:
        aliases:
          - api.pizza-shop.local
    depends_on:
      - pizza-shop.commande.db
      - pizza-shop.catalogue.db

  api.gateway:
    image: 'canals/php:latest'
    env_file: ./gate.env
    ports:
      - '3080:80'
      - '1543:443'
    volumes:
        - ../gateway.pizza-shop/public:/var/www/html
        - ../gateway.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      pizza-shop.net:
        aliases:
          - gateway.pizza-shop.local
    depends_on:
      - api.pizza-shop
      - api.pizza-auth



  # service sql pour le stockage des commandes -
  # utilisé par l'api order
  pizza-shop.commande.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./shop.env
    ports:
      - '18252:80'
    networks:
      - pizza-shop.net
    volumes:
      - ../shop.pizza-shop/sql:/var/sql

  # service sql pour le catalogue des pizzas -
  # utilisé par l'api order
  pizza-shop.catalogue.db:
    image: 'postgres:latest'
    env_file: ./cat.env
    ports:
      - '18251:80'
    networks:
      - pizza-shop.net
    volumes:
      - ../shop.pizza-shop/sql:/var/sql'
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - pizza-shop.net

#####################################
##  AUTH Service : service d'authentification JWT
##  api api.auth : auth, check, refresh de token JWT
##  utilise sa propre base de données
#####################################
  api.pizza-auth:
    image: 'canals/php:latest'
    env_file: ./auth.env
    ports:
      - '2780:80'
      - '2743:443'
    volumes:
      - ../auth.pizza-shop/public:/var/www/html
      - ../auth.pizza-shop:/var/www
    working_dir: /var/www
    networks:
      pizza-shop.net:
        aliases:
          - auth.pizza-shop.local
    depends_on:
      - pizza-shop.auth.db

  pizza-shop.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '3308:3306'
    networks:
      - pizza-shop.net
    volumes:
      - ../auth.pizza-shop/sql:/var/sql